packages:
  - "."

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  tailwindcss>nanoid: 3.3.7
  fast-xml-parser: 5.3.5
  path-to-regexp: 0.1.13
  lodash: 4.18.0
  lodash-es: 4.18.0
  tar: 7.5.22
