"use client";

import { Database, FlaskConical, Play, ShieldCheck, Workflow } from "lucide-react";
import { useWorkspace } from "@/stores/workspace";
import { Button } from "@/components/ui/button";

export function BacktesterView() {
  const { symbol, timeframe, setView } = useWorkspace();
  return <div className="flex h-full flex-col bg-background"><header className="flex h-11 shrink-0 items-center gap-2 border-b hairline bg-panel px-3"><FlaskConical className="h-4 w-4 text-research" /><div><div className="text-[12px] font-semibold">Research runs</div><div className="text-[9px] uppercase tracking-[0.13em] text-muted-foreground">Python worker · Rust deterministic engine</div></div><span className="ml-auto inline-flex items-center gap-1.5 rounded border hairline px-2 py-1 text-[10px] text-muted-foreground"><ShieldCheck className="h-3 w-3 text-research" />Read only</span></header><main className="grid min-h-0 flex-1 place-items-center overflow-auto p-4"><section className="w-full max-w-3xl border hairline bg-panel p-5 sm:p-7"><div className="grid gap-3 sm:grid-cols-3"><RunRequirement icon={<Workflow className="h-4 w-4 text-mdata" />} title="Validated artifact" value="Python strategy or indicator" detail="A source hash, runtime lock, parameter schema, and diagnostics are required before a run can be queued." /><RunRequirement icon={<Database className="h-4 w-4 text-mdata" />} title="Dataset manifest" value={`${symbol} · ${timeframe}`} detail="The active provider must return verified historical bars. Degraded or unavailable data is withheld." /><RunRequirement icon={<Play className="h-4 w-4 text-mdata" />} title="Execution policy" value="Next-bar open" detail="The Rust engine owns fills, costs, equity, drawdown, and result hashing; Python cannot directly fill an order." /></div><div className="mt-6 rounded border border-warn/30 bg-warn/5 p-4"><h2 className="text-sm font-semibold">No research job has been queued in this workspace.</h2><p className="mt-2 max-w-2xl text-[11px] leading-5 text-muted-foreground">The previous direct in-browser ZS backtest path is retired. A test run becomes available only after the Python research API, isolated worker, SQL queue, and Rust engine all report a healthy versioned contract. This prevents an unsafe local fallback or an unlabelled result.</p><Button onClick={() => setView("strategy")} className="mt-4 h-8 gap-1.5 text-[11px] bg-research text-research-foreground hover:bg-research/90"><FlaskConical className="h-3.5 w-3.5" />Open Python research workspace</Button></div><div className="mt-5 border-t hairline pt-4 text-[10px] leading-5 text-muted-foreground">Completed runs will display immutable artifact and conversion hashes, provider/native-symbol data manifest, worker and engine versions, execution policy, diagnostics, trade ledger, equity/drawdown, metrics, and validation-fixture evidence.</div></section></main></div>;
}

function RunRequirement({ icon, title, value, detail }: { icon: React.ReactNode; title: string; value: string; detail: string }) {
  return <article className="border hairline bg-surface/40 p-3"><div className="flex items-center gap-2">{icon}<span className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{title}</span></div><div className="mt-3 font-mono-num text-[12px] text-foreground">{value}</div><p className="mt-2 text-[10px] leading-4 text-muted-foreground">{detail}</p></article>;
}
