"use client";

import { BookOpenCheck, Database, FileCode2, GitFork, History, ShieldCheck } from "lucide-react";
import { useInstitutionalProtocol } from "@/stores/institutional-protocol";
import { Panel, Pill, StatRow } from "../terminal/primitives";

const stageTone: Record<string, "default" | "warn" | "pos" | "research" | "mdata"> = {
  NEEDS_SOURCE: "warn", NEEDS_RULE_CLARIFICATION: "warn", READY_FOR_DATA_REVIEW: "mdata", READY_FOR_GENERATION: "pos", BASELINE_REVIEWED: "pos", INCREMENTAL_RESEARCH: "research", PAUSED: "default", ARCHIVED: "default", DRAFT: "default", BASELINE_RUNNING: "research",
};

export function ProtocolJournalLedger() {
  const { projects, activeProjectId, selectProject } = useInstitutionalProtocol();
  const project = projects.find((item) => item.id === activeProjectId) ?? null;

  if (!projects.length) return <Panel className="p-4 text-[11px] text-muted-foreground">No Institutional Protocol record exists yet. Research Lab creates the cited source, three-rule spec, data assessment, generation artifacts, and subsequent audit trail.</Panel>;

  return <div className="space-y-3"><div className="flex flex-wrap gap-1.5">{projects.map((item) => <button key={item.id} onClick={() => selectProject(item.id)} className={`rounded border px-2 py-1 text-left text-[10px] transition-colors ${item.id === project?.id ? "border-research bg-research/5" : "hairline bg-surface hover:bg-hover"}`}><span className="font-medium">{item.name}</span><span className="ml-1 text-muted-foreground">r{item.revisions.at(-1)?.revision}</span></button>)}</div>{project && <Ledger project={project} />}</div>;
}

function Ledger({ project }: { project: ReturnType<typeof useInstitutionalProtocol.getState>["projects"][number] }) {
  const latestRevision = project.revisions.at(-1);
  const latestAssessment = project.assessments.at(-1);
  return <div className="space-y-2"><Panel className="p-3"><div className="flex flex-wrap items-center gap-2"><History className="h-4 w-4 text-research" /><span className="text-[12px] font-semibold">{project.name}</span><Pill tone={stageTone[project.stage] ?? "default"}>{project.stage.replaceAll("_", " ")}</Pill><span className="ml-auto text-[9.5px] text-muted-foreground">Created {new Date(project.createdAt).toLocaleString()}</span></div><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">Append-only local protocol ledger. Historical artifacts remain reconstructable; corrections create a later revision rather than rewriting prior evidence.</p></Panel>

    <section className="grid gap-2 lg:grid-cols-2"><Panel className="p-3"><div className="flex items-center gap-1.5"><BookOpenCheck className="h-3.5 w-3.5 text-research" /><h3 className="text-[10.5px] font-medium">1–2 · Cited research and rule spec</h3></div><div className="mt-2 space-y-1 text-[10px]"><p><span className="text-muted-foreground">Source:</span> {project.citation.author} ({project.citation.year}), {project.citation.title}</p><p className="break-all"><span className="text-muted-foreground">Reference:</span> {project.citation.reference}</p><p><span className="text-muted-foreground">Evidence:</span> {project.excerpts.length ? `${project.excerpts.length} confirmed excerpt(s)` : "No dedicated excerpt stored"}</p></div>{latestRevision && <div className="mt-2 grid gap-1 border-t hairline pt-2 text-[9.5px]"><div><span className="text-muted-foreground">Entry r{latestRevision.revision}</span><p>{latestRevision.entry}</p></div><div><span className="text-muted-foreground">Exit</span><p>{latestRevision.exit}</p></div><div><span className="text-muted-foreground">Sizing</span><p>{latestRevision.sizing}</p></div><p className="font-mono-num text-muted-foreground">hash {latestRevision.hash}</p></div>}</Panel>
      <Panel className="p-3"><div className="flex items-center gap-1.5"><Database className="h-3.5 w-3.5 text-mdata" /><h3 className="text-[10.5px] font-medium">3 · Data assessment</h3></div>{latestAssessment ? <div className="mt-2 space-y-1.5">{latestAssessment.requirements.map((requirement) => <div key={requirement.id} className="rounded border hairline bg-surface px-2 py-1"><div className="flex items-center gap-2"><span className="text-[9.5px] font-medium">{requirement.label}</span><Pill tone={requirement.coverage === "NATIVE_VERIFIED" ? "pos" : requirement.coverage === "IMPORT_REQUIRED" ? "warn" : "default"}>{requirement.coverage.replaceAll("_", " ")}</Pill></div><p className="mt-0.5 text-[9px] leading-relaxed text-muted-foreground">{requirement.risk}</p></div>)}<p className="text-[9.5px] text-muted-foreground">Dataset: {latestAssessment.selectedDataset ? `${latestAssessment.selectedDataset.provider} · ${latestAssessment.selectedDataset.symbol} · ${latestAssessment.selectedDataset.timeframe}` : "No baseline-eligible dataset selected"}</p></div> : <p className="mt-2 text-[10px] text-muted-foreground">No assessment recorded.</p>}</Panel></section>

    <Panel className="p-3"><div className="flex items-center gap-1.5"><FileCode2 className="h-3.5 w-3.5 text-research" /><h3 className="text-[10.5px] font-medium">4 · Generated code and approved assumptions</h3></div>{project.artifacts.length ? <div className="mt-2 space-y-2">{project.artifacts.map((artifact) => <div key={artifact.id} className="rounded border hairline bg-surface p-2"><div className="flex flex-wrap items-center gap-2"><span className="font-mono-num text-[9.5px]">{artifact.hash}</span><Pill tone={artifact.approval === "APPROVED" ? "pos" : "warn"}>{artifact.approval.replaceAll("_", " ")}</Pill><span className="text-[9px] text-muted-foreground">{new Date(artifact.createdAt).toLocaleString()}</span></div><p className="mt-1 text-[9.5px]">Assumptions: {artifact.assumptions.length ? artifact.assumptions.map((assumption) => `${assumption.approved ? "approved" : "unapproved"}: ${assumption.resolution}`).join(" · ") : "none"}</p>{artifact.unsupportedRequirements.length > 0 && <p className="mt-1 text-[9.5px] text-warn">Not approved: {artifact.unsupportedRequirements.join(" ")}</p>}</div>)}</div> : <p className="mt-2 text-[10px] text-muted-foreground">No generated artifact is recorded.</p>}</Panel>

    <Panel className="p-3"><div className="flex items-center gap-1.5"><GitFork className="h-3.5 w-3.5 text-research" /><h3 className="text-[10.5px] font-medium">5–6 · Baseline and incremental lineage</h3></div>{project.runs.length ? <div className="mt-2 space-y-2">{project.runs.map((run) => <div key={run.id} className="rounded border hairline bg-surface p-2"><div className="flex flex-wrap items-center gap-2"><Pill tone={run.runClass === "BASELINE" ? "research" : "warn"}>{run.runClass === "BASELINE" ? "BASELINE · NO OPTIMIZATION" : "TUNED · ONE VARIABLE"}</Pill><span className="font-mono-num text-[9.5px]">{run.resultHash}</span><span className="text-[9px] text-muted-foreground">{new Date(run.createdAt).toLocaleString()}</span></div><div className="mt-1 grid gap-1 text-[9.5px] sm:grid-cols-4"><StatRow label="Trades" value={String(run.metrics.totalTrades)} /><StatRow label="Expectancy" value={run.metrics.expectancy.toFixed(2)} /><StatRow label="Max DD" value={run.metrics.maxDrawdown.toFixed(0)} tone="neg" /><StatRow label="Adequacy" value={run.adequacy.status} tone={run.adequacy.status === "INSUFFICIENT" ? "neg" : run.adequacy.status === "LIMITED" ? "warn" : "pos"} /></div>{run.variableChange && <p className="mt-1 text-[9.5px]">One variable: <strong>{run.variableChange.label}</strong> — {run.variableChange.before} → {run.variableChange.after}. Parent: {run.parentRunId}</p>}</div>)}</div> : <p className="mt-2 text-[10px] text-muted-foreground">No baseline has completed. Complexity remains blocked.</p>}</Panel>

    <Panel className="p-3"><div className="flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5 text-research" /><h3 className="text-[10.5px] font-medium">Decision record</h3></div>{project.decisions.length ? <div className="mt-2 space-y-1">{project.decisions.map((decision) => <div key={decision.id} className="flex gap-2 text-[9.5px]"><span className="font-mono-num text-muted-foreground">{new Date(decision.createdAt).toLocaleString()}</span><span><strong>{decision.type.replaceAll("_", " ")}:</strong> {decision.detail}</span></div>)}</div> : <p className="mt-2 text-[10px] text-muted-foreground">Approvals and later decisions will appear here as immutable entries.</p>}</Panel>
  </div>;
}
