"use client";
import { useMemo, useState } from "react";
import { Copy, Eye, EyeOff, RotateCcw, Search, Settings2, Star, Trash2 } from "lucide-react";
import { useStudies } from "@/stores/studies";
import { usePanels } from "@/stores/panels";
import { INDICATOR_LIBRARY, searchIndicators, validateStudy, type IndicatorInstance } from "@/lib/indicator-library";
import type { ChartStudy } from "./terminal-chart";
export type IndicatorToggleId = "vwap" | "ema20" | "ema50" | "volume" | "profile";
type LegacyProps = { layers?: Record<IndicatorToggleId, boolean>; customStudies?: ChartStudy[]; onToggleLayer?: (id: IndicatorToggleId) => void; onCreate?: (study: ChartStudy) => void; onUpdate?: (study: ChartStudy) => void; onRemove?: (id: string) => void };

export function IndicatorsBrowser(_props: LegacyProps) {
  const { instances, favorites, recent, add, update, remove, duplicate, reset, toggleFavorite } = useStudies();
  const [filter, setFilter] = useState("All"), [query, setQuery] = useState(""), [selected, setSelected] = useState(0), [editing, setEditing] = useState<string | null>(null), [notice, setNotice] = useState("");
  const filtered = useMemo(() => searchIndicators(query).filter(item => filter === "All" || filter === "Favorites" && favorites.includes(item.id) || filter === "Recent" && recent.includes(item.id) || item.category === filter).sort((a, b) => filter === "Recent" ? recent.indexOf(a.id) - recent.indexOf(b.id) : 0), [query, filter, favorites, recent]);
  const study = instances.find(item => item.id === editing);
  const addIndicator = (id: string) => { if (instances.length >= 50) { setNotice("The chart supports up to 50 indicator instances."); return; } add(id); setNotice(`${INDICATOR_LIBRARY.find(item => item.id === id)?.name} added to chart.`); };
  if (study) return <StudySettings key={study.id} study={study} onSave={next => { update(next); if (next.kind === "python" && next.artifactId && JSON.stringify(next.inputs) !== JSON.stringify(study.inputs)) window.dispatchEvent(new CustomEvent("zterminal:rerun-python-indicator", { detail: { artifactId: next.artifactId, params: next.inputs } })); setEditing(null); }} onDuplicate={() => { duplicate(study.id); setEditing(null); }} onReset={() => reset(study.id)} onCancel={() => setEditing(null)} />;
  return <div className="zt-study-browser">
    <div className="zt-study-search"><Search size={14} /><input autoFocus aria-label="Search indicators" placeholder="Name, alias or calculation" value={query} onChange={event => { setQuery(event.target.value); setSelected(0); }} onKeyDown={event => { if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setSelected(index => Math.max(0, Math.min(filtered.length - 1, index + (event.key === "ArrowDown" ? 1 : -1)))); } if (event.key === "Enter" && filtered[selected]) { event.preventDefault(); addIndicator(filtered[selected].id); } if (event.key === "Escape") { if (query) { setQuery(""); setSelected(0); } else usePanels.getState().patch("indicators", { status: "closed" }); } }} aria-describedby="indicator-keyboard-help" /></div>
    <div className="zt-study-filters" aria-label="Indicator categories">{["All", "Favorites", "Recent", "Trend", "Volatility", "Volume", "On chart"].map(value => <button type="button" key={value} aria-pressed={filter === value} onClick={() => { setFilter(value); setSelected(0); }}>{value}{value === "On chart" ? ` (${instances.length})` : ""}</button>)}</div>
    <p id="indicator-keyboard-help" className="zt-study-help">↑ ↓ select · Enter adds · Esc clears or closes</p><p className="sr-only" aria-live="polite">{notice || (filtered[selected] ? `Selected ${filtered[selected].name}` : "No matching indicators")}</p>
    <div className="zt-study-list">{filter !== "On chart" ? filtered.length ? filtered.map((item, index) => <article key={item.id} data-selected={index === selected} className="zt-study-row"><div className="zt-study-row-top"><strong>{item.name}</strong><button type="button" aria-label={`${favorites.includes(item.id) ? "Unfavorite" : "Favorite"} ${item.name}`} aria-pressed={favorites.includes(item.id)} onClick={() => toggleFavorite(item.id)}><Star size={13} fill={favorites.includes(item.id) ? "currentColor" : "none"} /></button></div><p>{item.description}</p><div className="zt-study-row-bottom"><span>{item.category} / {item.display}</span><button type="button" onClick={() => addIndicator(item.id)} aria-label={`Add ${item.name}`}>+ Add</button></div></article>) : <p className="p-4 text-muted-foreground">No supported indicators match this view.</p> : instances.map(item => <article key={item.id} className="zt-study-row"><div className="zt-study-row-top"><strong style={{ color: item.outputs[0]?.color }}>{item.name}</strong><span>{typeof item.inputs.length === "number" ? `${item.inputs.length} bars` : item.kind}</span></div><div className="zt-study-row-bottom"><span>{item.enabled ? `${item.paneId} · ${item.outputs.filter(output => output.visible).length} plots` : "Hidden"}</span><div className="flex gap-2"><button type="button" onClick={() => update({ ...item, enabled: !item.enabled })} aria-label={`${item.enabled ? "Hide" : "Show"} ${item.name}`}>{item.enabled ? <Eye size={14} /> : <EyeOff size={14} />}</button><button type="button" aria-label={`Edit ${item.name}`} onClick={() => setEditing(item.id)}><Settings2 size={14} /></button><button type="button" aria-label={`Remove ${item.name}`} onClick={() => remove(item.id)}><Trash2 size={14} /></button></div></div></article>)}</div>
    <footer className="zt-study-help">Each instance owns its inputs, output styles, pane, scale, and timeframe visibility.</footer>
  </div>;
}

function StudySettings({ study, onSave, onDuplicate, onReset, onCancel }: { study: IndicatorInstance; onSave: (next: IndicatorInstance) => void; onDuplicate: () => void; onReset: () => void; onCancel: () => void }) {
  const [draft, setDraft] = useState(study), [tab, setTab] = useState<"inputs" | "style" | "visibility">("inputs"), [error, setError] = useState("");
  const definition = INDICATOR_LIBRARY.find(item => item.id === study.definitionId);
  return <form className="zt-study-settings" onSubmit={event => { event.preventDefault(); try { validateStudy(draft); onSave(draft); } catch (cause) { setError((cause as Error).message); } }}><span className="text-[9px] uppercase tracking-widest text-muted-foreground">Indicator instance / {study.kind}</span><h3>{study.name}</h3>
    <div className="zt-study-tabs" role="tablist" aria-label="Indicator settings sections">{(["inputs", "style", "visibility"] as const).map(value => <button type="button" role="tab" aria-selected={tab === value} key={value} onClick={() => setTab(value)}>{value}</button>)}</div>
    {tab === "inputs" && <div role="tabpanel"><label>Name<input maxLength={80} value={draft.name} onChange={event => setDraft(current => ({ ...current, name: event.target.value }))} /></label>{(definition?.inputs ?? []).map(input => <label key={input.id}>{input.label}<input type="number" min={input.min} max={input.max} step={input.step} value={String(draft.inputs[input.id] ?? input.defaultValue)} onChange={event => setDraft(current => ({ ...current, inputs: { ...current.inputs, [input.id]: Number(event.target.value) } }))} /></label>)}{Object.entries(draft.parameterSchema ?? {}).map(([id, spec]) => <label key={id}>{id}{spec.kind === "boolean" ? <input type="checkbox" checked={draft.inputs[id] === true} onChange={event => setDraft(current => ({ ...current, inputs: { ...current.inputs, [id]: event.target.checked } }))} /> : <input type={spec.kind === "string" ? "text" : "number"} min={spec.minimum ?? undefined} max={spec.maximum ?? undefined} step={spec.kind === "integer" ? 1 : "any"} value={String(draft.inputs[id] ?? spec.default)} onChange={event => setDraft(current => ({ ...current, inputs: { ...current.inputs, [id]: spec.kind === "string" ? event.target.value : Number(event.target.value) } }))} />}</label>)}</div>}
    {tab === "style" && <div role="tabpanel">{draft.outputs.length ? draft.outputs.map((output, index) => <fieldset className="zt-study-output" key={output.id}><legend>{output.label}</legend><label className="flex items-center gap-2"><input type="checkbox" checked={output.visible} onChange={event => setDraft(current => ({ ...current, outputs: current.outputs.map((item, itemIndex) => itemIndex === index ? { ...item, visible: event.target.checked } : item) }))} />Plot visible</label><label>Color<input type="color" value={output.color} onChange={event => setDraft(current => ({ ...current, outputs: current.outputs.map((item, itemIndex) => itemIndex === index ? { ...item, color: event.target.value } : item) }))} /></label><label>Width<select value={output.width} onChange={event => setDraft(current => ({ ...current, outputs: current.outputs.map((item, itemIndex) => itemIndex === index ? { ...item, width: Number(event.target.value) } : item) }))}>{[1, 2, 3, 4].map(value => <option key={value}>{value}</option>)}</select></label><label>Line style<select value={output.lineStyle} onChange={event => setDraft(current => ({ ...current, outputs: current.outputs.map((item, itemIndex) => itemIndex === index ? { ...item, lineStyle: event.target.value as typeof item.lineStyle } : item) }))}><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select></label></fieldset>) : <p>No configurable plot styles for this surface.</p>}</div>}
    {tab === "visibility" && <div role="tabpanel"><label className="flex items-center gap-2"><input type="checkbox" checked={draft.enabled} onChange={event => setDraft(current => ({ ...current, enabled: event.target.checked }))} />Enabled on chart</label><label>Pane<select value={draft.paneId} onChange={event => setDraft(current => ({ ...current, paneId: event.target.value }))}><option value="price">Price overlay</option><option value="indicator">Indicator pane</option>{study.kind === "volume" && <option value="volume">Volume pane</option>}</select></label><label>Price scale<select value={draft.priceScaleId} onChange={event => setDraft(current => ({ ...current, priceScaleId: event.target.value }))}><option value="right">Right</option><option value="left">Left</option><option value="indicator">Dedicated</option></select></label><label>Visible timeframes<select value={draft.visibility.timeframes === "all" ? "all" : draft.visibility.timeframes.join(",")} onChange={event => setDraft(current => ({ ...current, visibility: { timeframes: event.target.value === "all" ? "all" : event.target.value.split(",") as never } }))}><option value="all">All timeframes</option><option value="1m,5m,15m">Intraday fast</option><option value="30m,1h,4h">Intraday swing</option><option value="1d">Daily only</option></select></label></div>}
    {error ? <p role="alert">{error}</p> : null}<div className="zt-study-settings-actions"><button type="button" onClick={onCancel}>Cancel</button><button type="button" onClick={onDuplicate}><Copy size={12} />Duplicate</button><button type="button" onClick={() => { onReset(); onCancel(); }}><RotateCcw size={12} />Defaults</button><button type="submit">Apply</button></div>
  </form>;
}
