"use client";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { Copy, FilePlus2, Play, Save, Trash2, Download, Square } from "lucide-react";
import { useResearch } from "@/stores/research";
import { EXAMPLES } from "@/lib/local-research/examples";
import { intervalMs } from "@/lib/local-research/dataset";
const ResearchEditor = dynamic(() => import("./research-editor"), { ssr: false, loading: () => <p className="p-4 text-xs text-muted-foreground">Loading Python editor…</p> });
export function ResearchWorkbench() {
  const state = useResearch();
  const script = state.drafts[state.activeId];
  const [pairCode, setPairCode] = useState("");
  const [scriptAction, setScriptAction] = useState<"rename" | "copy" | "delete" | null>(null);
  const [name, setName] = useState("");
  const [storageFailed, setStorageFailed] = useState(false);
  const [paramsText, setParamsText] = useState(() => JSON.stringify(state.params));
  const [paramsError, setParamsError] = useState("");
  const busy = state.job && !["complete", "failed", "cancelled"].includes(state.job.stage);
  useEffect(() => {
    const warn = () => setStorageFailed(true);
    window.addEventListener("zterminal:draft-storage-failed", warn);
    const stopHydration = useResearch.persist.onFinishHydration(current => setParamsText(JSON.stringify(current.params)));
    void useResearch.persist.rehydrate();
    return () => { window.removeEventListener("zterminal:draft-storage-failed", warn); stopHydration(); };
  }, []);
  const period = (days: number) => { const interval = intervalMs(state.config.timeframe), to = Math.floor(Date.now() / interval) * interval; state.configure({ from: to - days * 86400000, to }); };
  useEffect(() => { const timer = setTimeout(() => void useResearch.getState().verifyInstrument(), 500); return () => clearTimeout(timer); }, [state.config.provider, state.config.symbol]);
  const exportSource = () => {
    const url = URL.createObjectURL(new Blob([script.source], { type: "text/x-python" }));
    const link = document.createElement("a"); link.href = url; link.download = `${script.name.replace(/[^a-z0-9_-]/gi, "_")}.py`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className="zt-research-workbench">
    <div className="zt-research-files"><select aria-label="Current research script" value={state.activeId} onChange={e => state.selectScript(e.target.value)}>{Object.values(state.drafts).sort((a, b) => b.updatedAt - a.updatedAt).map(p => <option key={p.id} value={p.id}>{p.name}{p.source !== p.savedSource ? " •" : ""}</option>)}</select><button aria-label="New script" title="New script" onClick={() => state.createScript()}><FilePlus2 size={14} /></button><button aria-label="Save script" title="Save (Ctrl/Cmd+S)" onClick={() => state.save()} disabled={state.connection !== "connected"}><Save size={14} /></button><button aria-label="Save As or duplicate script" title="Save As / duplicate" onClick={() => { setName(`${script.name} copy`); setScriptAction("copy"); }}><Copy size={14} /></button><button aria-label="Download Python source" title="Export source" onClick={exportSource}><Download size={14} /></button></div>
    <div className="zt-research-script-meta"><button onClick={() => { setName(script.name); setScriptAction("rename"); }}>Rename</button><span>{script.revision ? `Revision ${script.revision}` : "Unsaved script"} {script.source !== script.savedSource ? "· Draft changes" : "· Saved"}</span><button aria-label="Delete script" onClick={() => setScriptAction("delete")}><Trash2 size={12} /></button></div>
    {scriptAction && <form className="zt-research-inline-form" onSubmit={e => { e.preventDefault(); if (scriptAction === "delete") void state.deleteScript(); else if (scriptAction === "copy" && state.connection !== "connected") state.createScript(name, script.source); else if (scriptAction === "rename" && !script.revision) useResearch.setState(s => ({ drafts: { ...s.drafts, [s.activeId]: { ...s.drafts[s.activeId], name } } })); else void state.save(name, scriptAction === "copy"); setScriptAction(null); }}>
      {scriptAction === "delete" ? <p>Delete “{script.name}”? Archived runs and saved revisions remain in the helper.</p> : <label>Script name<input autoFocus required maxLength={120} value={name} onChange={e => setName(e.target.value)} /></label>}<button type="button" onClick={() => setScriptAction(null)}>Cancel</button><button type="submit">{scriptAction === "delete" ? "Delete script" : "Apply"}</button>
    </form>}
    {state.connection !== "connected" && <div className="zt-helper-pairing"><div><b>Local Python / private preview</b><span>{state.connection === "unchecked" ? "Install and pair the Windows helper once." : state.connection.replaceAll("_", " ")}</span></div><p>Scripts run on your computer with your permissions. Process limits are not a secure sandbox. Run code you trust.</p><div className="flex gap-2"><input aria-label="Helper pairing code" placeholder="8-digit pairing code" value={pairCode} inputMode="numeric" maxLength={8} onChange={e => setPairCode(e.target.value)} /><button disabled={state.connection === "checking"} onClick={() => state.connect(pairCode || undefined)}>{pairCode ? "Pair helper" : "Connect"}</button></div><small>Public installer availability remains gated. Use the supplied private Windows package.</small></div>}
    <div className="zt-research-runbar"><button className="zt-backtest-button" disabled={(state.connection !== "connected" || !state.instrument || state.instrument.symbol !== state.config.symbol || state.instrument.provider !== state.config.provider) && !busy} onClick={() => busy ? state.cancel() : state.run()}>{busy ? <Square size={12} /> : <Play size={12} />}{busy ? "Cancel" : "Backtest"}</button><span>{state.config.symbol} / {state.config.timeframe}</span><span>{state.config.initialCapital.toLocaleString()} quote</span></div>
    <details className="zt-research-config"><summary>Dataset & capital <span>{Math.round((state.config.to - state.config.from) / 86400000)} days · UTC</span></summary><div className="zt-research-form-grid"><label>Provider<select value={state.config.provider} onChange={e => state.configure({ provider: e.target.value as "gateio" | "binance", symbol: e.target.value === "gateio" ? "BTC_USDT" : "BTCUSDT" })}><option value="gateio">Gate.io</option><option value="binance">Binance USDⓈ-M</option></select></label><label>Native symbol<input value={state.config.symbol} onChange={e => state.configure({ symbol: e.target.value.toUpperCase() })} /></label><label>Timeframe<select value={state.config.timeframe} onChange={e => { const interval = intervalMs(e.target.value); state.configure({ timeframe: e.target.value, from: Math.floor(state.config.from / interval) * interval, to: Math.floor(state.config.to / interval) * interval }); }}>{["1m", "5m", "15m", "30m", "1h", "4h", "1d"].map(tf => <option key={tf}>{tf}</option>)}</select></label><label>Capital<input type="number" min={1} value={state.config.initialCapital} onChange={e => state.configure({ initialCapital: Number(e.target.value) })} /></label><label>From (UTC)<input type="datetime-local" value={new Date(state.config.from).toISOString().slice(0, 16)} onChange={e => { const from = Date.parse(`${e.target.value}Z`); if (Number.isFinite(from)) state.configure({ from }); }} /></label><label>To, exclusive (UTC)<input type="datetime-local" value={new Date(state.config.to).toISOString().slice(0, 16)} onChange={e => { const to = Date.parse(`${e.target.value}Z`); if (Number.isFinite(to)) state.configure({ to }); }} /></label></div><div className="flex gap-3"><button onClick={() => period(90)}>90 days</button><button onClick={() => period(730)}>2 years</button></div></details>
    <details className="zt-research-config"><summary>Advanced / execution assumptions</summary><div className="zt-research-form-grid">{([["feeBps", "Fees (bps)"], ["slippageBps", "Slippage (bps)"], ["allocation", "Cash allocation (fraction)"]] as const).map(([key, label]) => <label key={key}>{label}<input type="number" step="any" value={state.config[key]} onChange={e => state.configure({ [key]: Number(e.target.value) })} /></label>)}<label>Direction<select value={state.config.direction} onChange={e => state.configure({ direction: e.target.value as "long" | "both" })}><option value="long">Long only</option><option value="both">Long + short</option></select></label></div><label className="zt-params-json">Strategy parameters (JSON object)<textarea value={paramsText} spellCheck={false} rows={3} onChange={e => setParamsText(e.target.value)} onBlur={() => { try { const parsed = JSON.parse(paramsText); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object" || Object.entries(parsed).some(([key, value]) => key.length > 80 || !["string", "number", "boolean"].includes(typeof value) || typeof value === "number" && !Number.isFinite(value))) throw new Error("Use a JSON object with finite number, string, or boolean values."); useResearch.setState({ params: parsed }); setParamsError(""); } catch (error) { setParamsError((error as Error).message); } }} /></label>{paramsError && <p role="alert">{paramsError} The last valid parameters remain active.</p>}<p>{state.instrument ? `Verified quantity units: multiplier ${state.instrument.multiplier}, quantity step ${state.instrument.quantityStep}.` : "Instrument units have not been verified."} <button onClick={() => state.verifyInstrument()}>Verify units</button></p><p>One unlevered position. Signals at completed-bar close fill at the next open. No funding, liquidation or margin model. Open positions remain marked to market.</p></details>
    <div className="zt-research-editor-tools"><select aria-label="Open educational example" value="" onChange={e => { const example = EXAMPLES.find(p => p.id === e.target.value); if (example) state.createScript(example.name, example.source); }}><option value="">Educational examples…</option>{EXAMPLES.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><label><input type="checkbox" checked={state.minimap} onChange={e => useResearch.setState({ minimap: e.target.checked })} />Minimap</label><span>Ctrl/⌘ ↵</span></div>
    <div className="zt-research-editor"><ResearchEditor /></div>
    <div className="zt-research-status" aria-live="polite">{busy ? state.job!.stage.replaceAll("_", " ") : state.job?.stage === "complete" ? "Result archived locally" : "Python / ZTerminal SDK v1"}{storageFailed && <p role="alert">Browser draft recovery is unavailable. Export your source to preserve unsaved work.</p>}{state.error && <p role="alert">{state.error}</p>}{state.diagnostic?.line && <button onClick={() => document.querySelector<HTMLElement>(".monaco-editor textarea")?.focus()}>Inspect line {state.diagnostic.line}</button>}</div>
  </div>;
}
